feat: initial working version with job (#1)

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -7,24 +7,41 @@ filters: &filters
   tags:
     only: /.*/
 
+tag-filters: &tag-filters
+  branches:
+    ignore: /.*/
+  tags:
+    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
+
 jobs:
-  # Create a job to test the commands of your orbs.
-  # You may want to add additional validation steps to ensure the commands are working as expected.
   command-tests:
-    docker:
-      - image: cimg/base:current
+    executor: gomplate/gomplate
     steps:
-      - checkout
-      # Run your orb's commands to validate them.
-      - gomplate/greet
+      - run:
+          name: "Generate test template"
+          command: |
+            echo "Hello, {{ .Values.name }}!" > test.txt.tmpl
+            echo "name: CircleCI" > Values.yaml
+      - gomplate/render-template:
+          template-file: test.txt.tmpl
+          output-file: test.txt
+          contexts: Values.yaml
+      - run:
+          name: "Check test template output"
+          command: |
+            cat test.txt
+            if [ "$(cat test.txt)" != "Hello, CircleCI!" ]; then
+              echo "Test failed"
+              exit 1
+            fi
+
 workflows:
   test-deploy:
     jobs:
-      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
       - command-tests:
           filters: *filters
       - orb-tools/pack:
-          filters: *filters
+          filters: *tag-filters
       - orb-tools/publish:
           orb-name: xavientois/gomplate
           vcs-type: << pipeline.project.type >>
@@ -33,10 +50,4 @@ workflows:
             - orb-tools/pack
             - command-tests
           context: orb-publishing
-          filters:
-            branches:
-              ignore: /.*/
-            tags:
-              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
-
-# VS Code Extension Version: 1.4.0
+          filters: *tag-filters
